site_name: ServiceNow MCP System Documentation
nav:
  - Home: index.md
  - Architecture: ARCHITECTURE.md
  - Deployment: DEPLOYMENT.md
  - Observability Guide: OBSERVABILITY_GUIDE.md
  - API and MCP Usage: api_mcp_usage.md
extra_javascript:
  - docs/_assets/mermaid-init.js
theme:
  name: readthedocs
