site_name: Agentic Solutions Documentation
nav:
  - Home: index.md
  - Guides:
    - ServiceNow API and MCP SSE: api_mcp_usage.md
  - Architecture: ARCHITECTURE.md
  - Deployment: DEPLOYMENT.md
  - Observability: OBSERVABILITY_GUIDE.md
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - docs/_assets/mermaid-init.js
theme:
  name: mkdocs
