# ServiceNow MCP Configuration for magentic-ui
# This adds ServiceNow agents while keeping default agents (web_surfer, coder_agent, etc.)

# Model client configuration (using OpenAI GPT-4o by default)
gpt4o_client: &gpt4o_client
  provider: OpenAIChatCompletionClient
  config:
    model: gpt-4o-2024-08-06
    api_key: null
    base_url: null
  max_retries: 5

# Default agent configurations
orchestrator_client: *gpt4o_client
coder_client: *gpt4o_client
web_surfer_client: *gpt4o_client
file_surfer_client: *gpt4o_client
action_guard_client: *gpt4o_client
plan_learning_client: *gpt4o_client

# Custom MCP Agents for ServiceNow APIs
mcp_agent_configs:
  - name: servicenow_table_agent
    description: "ServiceNow Table API agent with CRUD operations on ServiceNow tables"
    model_client:
      provider: OpenAIChatCompletionClient
      config:
        model: gpt-4o-2024-08-06
        api_key: null
        base_url: null
      max_retries: 5
    system_message: |-
      You are the ServiceNow Table API agent. You have direct access to ServiceNow's Table API.
      
      You can:
      - Query records from any ServiceNow table (incidents, users, changes, etc.)
      - Create new records
      - Update existing records  
      - Delete records
      - Perform aggregate queries
      
      Always use the appropriate table names (e.g., 'incident', 'sys_user', 'change_request').
      When querying, use ServiceNow's encoded query syntax when needed.
    reflect_on_tool_use: false
    mcp_servers:
      - server_name: ServiceNow_Table_API
        server_params:
          type: HttpServerParams
          url: "http://localhost:3001/mcp/"

  - name: servicenow_knowledge_agent
    description: "ServiceNow Knowledge Management API agent for searching and managing knowledge articles"
    model_client:
      provider: OpenAIChatCompletionClient
      config:
        model: gpt-4o-2024-08-06
        api_key: null
        base_url: null
      max_retries: 5
    system_message: |-
      You are the ServiceNow Knowledge Management API agent. You have direct access to ServiceNow's Knowledge Management REST API.
      
      You can:
      - Search knowledge articles by query terms
      - Get specific articles by ID
      - Find featured articles
      - Get most viewed articles
      - Get recent articles
      - Create and update knowledge articles
      
      Use the sn_km_api namespace for knowledge management operations.
      Always provide helpful, accurate information from the knowledge base.
    reflect_on_tool_use: false
    mcp_servers:
      - server_name: ServiceNow_Knowledge_API
        server_params:
          type: HttpServerParams
          url: "http://localhost:3002/mcp/"