global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # ServiceNow MCP System components
  - job_name: 'servicenow-mcp-system'
    static_configs:
      - targets: ['host.docker.internal:8010']  # Prometheus server in observability.py
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MCP agents
  - job_name: 'mcp-table-agent'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mcp-knowledge-agent'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Magentic-UI
  - job_name: 'magentic-ui'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: '/metrics'
    scrape_interval: 15s